// Copyright (c) 2019 Chris Ohk, Youngjoong Kim, SeungHyun Jeon

// We are making my contributions/submissions to this project solely in our
// personal capacity and are not conveying any rights to any intellectual
// property of any third parties.

#ifndef ROSETTASTONE_DECK_STRING_HPP
#define ROSETTASTONE_DECK_STRING_HPP

#include <Rosetta/Accounts/DeckInfo.hpp>

namespace RosettaStone
{
class DeckString
{
 public:
    //! Decodes a deck code and returns the deck that contains some cards.
    //! \param deckCode The deck code generated by Hearthstone.
    static DeckInfo DecodeDeckCode(const std::string& deckCode);
};
}  // namespace RosettaStone

#endif  // ROSETTASTONE_DECK_STRING_HPP
