// Copyright (c) 2019 Chris Ohk, Youngjoong Kim, SeungHyun Jeon

// We are making my contributions/submissions to this project solely in our
// personal capacity and are not conveying any rights to any intellectual
// property of any third parties.

#ifndef ROSETTASTONE_JSON_SERIALIZER_HPP
#define ROSETTASTONE_JSON_SERIALIZER_HPP

#include <json/json.hpp>

namespace RosettaStone
{
class JSONSerializer
{
 public:
    //! Decodes a deck code and returns the deck that contains some cards.
    //! \param deckCode The deck code generated by Hearthstone.
    //! \return The decoded deck that contains card information.
    static DeckInfo Decode(const std::string& deckCode);
};
}  // namespace RosettaStone

#endif  // ROSETTASTONE_JSON_SERIALIZER_HPP
