FROM ubuntu:18.04
MAINTAINER Chris Ohk <utilforever@gmail.com>

RUN apt-get update -yq && \
    apt-get install -yq build-essential python-dev python-pip python3-dev python3-pip python3-venv cmake

ADD . /app

WORKDIR /app/build
RUN cmake .. && \
    make -j`nproc` && \
    make install && \
    bin/UnitTests

WORKDIR /
