// This file was automatically generated by make_macros.py

#pragma once

#ifndef BETTER_ENUMS_MACRO_FILE_H
#define BETTER_ENUMS_MACRO_FILE_H

#define BETTER_ENUMS_PP_MAP(macro, data, ...) \
    BETTER_ENUMS_ID( \
        BETTER_ENUMS_APPLY( \
            BETTER_ENUMS_PP_MAP_VAR_COUNT, \
            BETTER_ENUMS_PP_COUNT(__VA_ARGS__)) \
        (macro, data, __VA_ARGS__))

#define BETTER_ENUMS_PP_MAP_VAR_COUNT(count) BETTER_ENUMS_M ## count

#define BETTER_ENUMS_APPLY(macro, ...) BETTER_ENUMS_ID(macro(__VA_ARGS__))

#define BETTER_ENUMS_ID(x) x

#define BETTER_ENUMS_M1(m, d, x) m(d,0,x)
#define BETTER_ENUMS_M2(m,d,x,...) m(d,1,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M1(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M3(m,d,x,...) m(d,2,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M2(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M4(m,d,x,...) m(d,3,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M3(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M5(m,d,x,...) m(d,4,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M4(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M6(m,d,x,...) m(d,5,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M5(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M7(m,d,x,...) m(d,6,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M6(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M8(m,d,x,...) m(d,7,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M7(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M9(m,d,x,...) m(d,8,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M8(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M10(m,d,x,...) m(d,9,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M9(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M11(m,d,x,...) m(d,10,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M10(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M12(m,d,x,...) m(d,11,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M11(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M13(m,d,x,...) m(d,12,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M12(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M14(m,d,x,...) m(d,13,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M13(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M15(m,d,x,...) m(d,14,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M14(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M16(m,d,x,...) m(d,15,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M15(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M17(m,d,x,...) m(d,16,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M16(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M18(m,d,x,...) m(d,17,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M17(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M19(m,d,x,...) m(d,18,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M18(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M20(m,d,x,...) m(d,19,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M19(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M21(m,d,x,...) m(d,20,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M20(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M22(m,d,x,...) m(d,21,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M21(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M23(m,d,x,...) m(d,22,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M22(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M24(m,d,x,...) m(d,23,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M23(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M25(m,d,x,...) m(d,24,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M24(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M26(m,d,x,...) m(d,25,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M25(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M27(m,d,x,...) m(d,26,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M26(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M28(m,d,x,...) m(d,27,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M27(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M29(m,d,x,...) m(d,28,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M28(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M30(m,d,x,...) m(d,29,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M29(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M31(m,d,x,...) m(d,30,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M30(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M32(m,d,x,...) m(d,31,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M31(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M33(m,d,x,...) m(d,32,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M32(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M34(m,d,x,...) m(d,33,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M33(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M35(m,d,x,...) m(d,34,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M34(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M36(m,d,x,...) m(d,35,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M35(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M37(m,d,x,...) m(d,36,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M36(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M38(m,d,x,...) m(d,37,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M37(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M39(m,d,x,...) m(d,38,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M38(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M40(m,d,x,...) m(d,39,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M39(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M41(m,d,x,...) m(d,40,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M40(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M42(m,d,x,...) m(d,41,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M41(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M43(m,d,x,...) m(d,42,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M42(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M44(m,d,x,...) m(d,43,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M43(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M45(m,d,x,...) m(d,44,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M44(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M46(m,d,x,...) m(d,45,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M45(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M47(m,d,x,...) m(d,46,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M46(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M48(m,d,x,...) m(d,47,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M47(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M49(m,d,x,...) m(d,48,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M48(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M50(m,d,x,...) m(d,49,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M49(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M51(m,d,x,...) m(d,50,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M50(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M52(m,d,x,...) m(d,51,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M51(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M53(m,d,x,...) m(d,52,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M52(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M54(m,d,x,...) m(d,53,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M53(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M55(m,d,x,...) m(d,54,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M54(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M56(m,d,x,...) m(d,55,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M55(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M57(m,d,x,...) m(d,56,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M56(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M58(m,d,x,...) m(d,57,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M57(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M59(m,d,x,...) m(d,58,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M58(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M60(m,d,x,...) m(d,59,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M59(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M61(m,d,x,...) m(d,60,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M60(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M62(m,d,x,...) m(d,61,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M61(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M63(m,d,x,...) m(d,62,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M62(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M64(m,d,x,...) m(d,63,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M63(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M65(m,d,x,...) m(d,64,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M64(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M66(m,d,x,...) m(d,65,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M65(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M67(m,d,x,...) m(d,66,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M66(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M68(m,d,x,...) m(d,67,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M67(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M69(m,d,x,...) m(d,68,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M68(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M70(m,d,x,...) m(d,69,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M69(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M71(m,d,x,...) m(d,70,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M70(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M72(m,d,x,...) m(d,71,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M71(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M73(m,d,x,...) m(d,72,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M72(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M74(m,d,x,...) m(d,73,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M73(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M75(m,d,x,...) m(d,74,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M74(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M76(m,d,x,...) m(d,75,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M75(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M77(m,d,x,...) m(d,76,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M76(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M78(m,d,x,...) m(d,77,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M77(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M79(m,d,x,...) m(d,78,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M78(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M80(m,d,x,...) m(d,79,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M79(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M81(m,d,x,...) m(d,80,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M80(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M82(m,d,x,...) m(d,81,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M81(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M83(m,d,x,...) m(d,82,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M82(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M84(m,d,x,...) m(d,83,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M83(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M85(m,d,x,...) m(d,84,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M84(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M86(m,d,x,...) m(d,85,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M85(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M87(m,d,x,...) m(d,86,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M86(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M88(m,d,x,...) m(d,87,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M87(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M89(m,d,x,...) m(d,88,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M88(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M90(m,d,x,...) m(d,89,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M89(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M91(m,d,x,...) m(d,90,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M90(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M92(m,d,x,...) m(d,91,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M91(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M93(m,d,x,...) m(d,92,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M92(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M94(m,d,x,...) m(d,93,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M93(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M95(m,d,x,...) m(d,94,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M94(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M96(m,d,x,...) m(d,95,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M95(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M97(m,d,x,...) m(d,96,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M96(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M98(m,d,x,...) m(d,97,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M97(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M99(m,d,x,...) m(d,98,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M98(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M100(m,d,x,...) m(d,99,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M99(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M101(m,d,x,...) m(d,100,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M100(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M102(m,d,x,...) m(d,101,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M101(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M103(m,d,x,...) m(d,102,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M102(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M104(m,d,x,...) m(d,103,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M103(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M105(m,d,x,...) m(d,104,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M104(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M106(m,d,x,...) m(d,105,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M105(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M107(m,d,x,...) m(d,106,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M106(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M108(m,d,x,...) m(d,107,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M107(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M109(m,d,x,...) m(d,108,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M108(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M110(m,d,x,...) m(d,109,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M109(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M111(m,d,x,...) m(d,110,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M110(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M112(m,d,x,...) m(d,111,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M111(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M113(m,d,x,...) m(d,112,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M112(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M114(m,d,x,...) m(d,113,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M113(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M115(m,d,x,...) m(d,114,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M114(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M116(m,d,x,...) m(d,115,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M115(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M117(m,d,x,...) m(d,116,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M116(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M118(m,d,x,...) m(d,117,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M117(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M119(m,d,x,...) m(d,118,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M118(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M120(m,d,x,...) m(d,119,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M119(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M121(m,d,x,...) m(d,120,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M120(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M122(m,d,x,...) m(d,121,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M121(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M123(m,d,x,...) m(d,122,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M122(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M124(m,d,x,...) m(d,123,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M123(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M125(m,d,x,...) m(d,124,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M124(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M126(m,d,x,...) m(d,125,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M125(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M127(m,d,x,...) m(d,126,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M126(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M128(m,d,x,...) m(d,127,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M127(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M129(m,d,x,...) m(d,128,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M128(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M130(m,d,x,...) m(d,129,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M129(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M131(m,d,x,...) m(d,130,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M130(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M132(m,d,x,...) m(d,131,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M131(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M133(m,d,x,...) m(d,132,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M132(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M134(m,d,x,...) m(d,133,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M133(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M135(m,d,x,...) m(d,134,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M134(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M136(m,d,x,...) m(d,135,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M135(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M137(m,d,x,...) m(d,136,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M136(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M138(m,d,x,...) m(d,137,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M137(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M139(m,d,x,...) m(d,138,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M138(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M140(m,d,x,...) m(d,139,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M139(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M141(m,d,x,...) m(d,140,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M140(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M142(m,d,x,...) m(d,141,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M141(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M143(m,d,x,...) m(d,142,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M142(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M144(m,d,x,...) m(d,143,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M143(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M145(m,d,x,...) m(d,144,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M144(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M146(m,d,x,...) m(d,145,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M145(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M147(m,d,x,...) m(d,146,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M146(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M148(m,d,x,...) m(d,147,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M147(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M149(m,d,x,...) m(d,148,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M148(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M150(m,d,x,...) m(d,149,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M149(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M151(m,d,x,...) m(d,150,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M150(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M152(m,d,x,...) m(d,151,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M151(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M153(m,d,x,...) m(d,152,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M152(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M154(m,d,x,...) m(d,153,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M153(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M155(m,d,x,...) m(d,154,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M154(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M156(m,d,x,...) m(d,155,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M155(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M157(m,d,x,...) m(d,156,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M156(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M158(m,d,x,...) m(d,157,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M157(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M159(m,d,x,...) m(d,158,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M158(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M160(m,d,x,...) m(d,159,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M159(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M161(m,d,x,...) m(d,160,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M160(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M162(m,d,x,...) m(d,161,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M161(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M163(m,d,x,...) m(d,162,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M162(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M164(m,d,x,...) m(d,163,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M163(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M165(m,d,x,...) m(d,164,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M164(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M166(m,d,x,...) m(d,165,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M165(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M167(m,d,x,...) m(d,166,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M166(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M168(m,d,x,...) m(d,167,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M167(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M169(m,d,x,...) m(d,168,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M168(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M170(m,d,x,...) m(d,169,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M169(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M171(m,d,x,...) m(d,170,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M170(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M172(m,d,x,...) m(d,171,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M171(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M173(m,d,x,...) m(d,172,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M172(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M174(m,d,x,...) m(d,173,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M173(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M175(m,d,x,...) m(d,174,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M174(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M176(m,d,x,...) m(d,175,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M175(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M177(m,d,x,...) m(d,176,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M176(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M178(m,d,x,...) m(d,177,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M177(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M179(m,d,x,...) m(d,178,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M178(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M180(m,d,x,...) m(d,179,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M179(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M181(m,d,x,...) m(d,180,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M180(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M182(m,d,x,...) m(d,181,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M181(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M183(m,d,x,...) m(d,182,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M182(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M184(m,d,x,...) m(d,183,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M183(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M185(m,d,x,...) m(d,184,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M184(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M186(m,d,x,...) m(d,185,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M185(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M187(m,d,x,...) m(d,186,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M186(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M188(m,d,x,...) m(d,187,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M187(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M189(m,d,x,...) m(d,188,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M188(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M190(m,d,x,...) m(d,189,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M189(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M191(m,d,x,...) m(d,190,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M190(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M192(m,d,x,...) m(d,191,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M191(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M193(m,d,x,...) m(d,192,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M192(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M194(m,d,x,...) m(d,193,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M193(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M195(m,d,x,...) m(d,194,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M194(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M196(m,d,x,...) m(d,195,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M195(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M197(m,d,x,...) m(d,196,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M196(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M198(m,d,x,...) m(d,197,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M197(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M199(m,d,x,...) m(d,198,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M198(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M200(m,d,x,...) m(d,199,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M199(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M201(m,d,x,...) m(d,200,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M200(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M202(m,d,x,...) m(d,201,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M201(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M203(m,d,x,...) m(d,202,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M202(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M204(m,d,x,...) m(d,203,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M203(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M205(m,d,x,...) m(d,204,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M204(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M206(m,d,x,...) m(d,205,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M205(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M207(m,d,x,...) m(d,206,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M206(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M208(m,d,x,...) m(d,207,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M207(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M209(m,d,x,...) m(d,208,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M208(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M210(m,d,x,...) m(d,209,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M209(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M211(m,d,x,...) m(d,210,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M210(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M212(m,d,x,...) m(d,211,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M211(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M213(m,d,x,...) m(d,212,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M212(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M214(m,d,x,...) m(d,213,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M213(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M215(m,d,x,...) m(d,214,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M214(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M216(m,d,x,...) m(d,215,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M215(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M217(m,d,x,...) m(d,216,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M216(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M218(m,d,x,...) m(d,217,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M217(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M219(m,d,x,...) m(d,218,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M218(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M220(m,d,x,...) m(d,219,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M219(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M221(m,d,x,...) m(d,220,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M220(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M222(m,d,x,...) m(d,221,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M221(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M223(m,d,x,...) m(d,222,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M222(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M224(m,d,x,...) m(d,223,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M223(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M225(m,d,x,...) m(d,224,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M224(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M226(m,d,x,...) m(d,225,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M225(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M227(m,d,x,...) m(d,226,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M226(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M228(m,d,x,...) m(d,227,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M227(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M229(m,d,x,...) m(d,228,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M228(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M230(m,d,x,...) m(d,229,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M229(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M231(m,d,x,...) m(d,230,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M230(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M232(m,d,x,...) m(d,231,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M231(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M233(m,d,x,...) m(d,232,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M232(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M234(m,d,x,...) m(d,233,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M233(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M235(m,d,x,...) m(d,234,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M234(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M236(m,d,x,...) m(d,235,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M235(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M237(m,d,x,...) m(d,236,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M236(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M238(m,d,x,...) m(d,237,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M237(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M239(m,d,x,...) m(d,238,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M238(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M240(m,d,x,...) m(d,239,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M239(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M241(m,d,x,...) m(d,240,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M240(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M242(m,d,x,...) m(d,241,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M241(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M243(m,d,x,...) m(d,242,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M242(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M244(m,d,x,...) m(d,243,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M243(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M245(m,d,x,...) m(d,244,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M244(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M246(m,d,x,...) m(d,245,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M245(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M247(m,d,x,...) m(d,246,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M246(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M248(m,d,x,...) m(d,247,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M247(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M249(m,d,x,...) m(d,248,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M248(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M250(m,d,x,...) m(d,249,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M249(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M251(m,d,x,...) m(d,250,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M250(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M252(m,d,x,...) m(d,251,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M251(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M253(m,d,x,...) m(d,252,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M252(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M254(m,d,x,...) m(d,253,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M253(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M255(m,d,x,...) m(d,254,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M254(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M256(m,d,x,...) m(d,255,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M255(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M257(m,d,x,...) m(d,256,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M256(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M258(m,d,x,...) m(d,257,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M257(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M259(m,d,x,...) m(d,258,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M258(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M260(m,d,x,...) m(d,259,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M259(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M261(m,d,x,...) m(d,260,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M260(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M262(m,d,x,...) m(d,261,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M261(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M263(m,d,x,...) m(d,262,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M262(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M264(m,d,x,...) m(d,263,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M263(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M265(m,d,x,...) m(d,264,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M264(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M266(m,d,x,...) m(d,265,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M265(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M267(m,d,x,...) m(d,266,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M266(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M268(m,d,x,...) m(d,267,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M267(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M269(m,d,x,...) m(d,268,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M268(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M270(m,d,x,...) m(d,269,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M269(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M271(m,d,x,...) m(d,270,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M270(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M272(m,d,x,...) m(d,271,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M271(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M273(m,d,x,...) m(d,272,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M272(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M274(m,d,x,...) m(d,273,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M273(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M275(m,d,x,...) m(d,274,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M274(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M276(m,d,x,...) m(d,275,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M275(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M277(m,d,x,...) m(d,276,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M276(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M278(m,d,x,...) m(d,277,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M277(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M279(m,d,x,...) m(d,278,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M278(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M280(m,d,x,...) m(d,279,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M279(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M281(m,d,x,...) m(d,280,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M280(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M282(m,d,x,...) m(d,281,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M281(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M283(m,d,x,...) m(d,282,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M282(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M284(m,d,x,...) m(d,283,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M283(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M285(m,d,x,...) m(d,284,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M284(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M286(m,d,x,...) m(d,285,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M285(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M287(m,d,x,...) m(d,286,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M286(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M288(m,d,x,...) m(d,287,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M287(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M289(m,d,x,...) m(d,288,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M288(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M290(m,d,x,...) m(d,289,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M289(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M291(m,d,x,...) m(d,290,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M290(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M292(m,d,x,...) m(d,291,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M291(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M293(m,d,x,...) m(d,292,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M292(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M294(m,d,x,...) m(d,293,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M293(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M295(m,d,x,...) m(d,294,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M294(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M296(m,d,x,...) m(d,295,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M295(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M297(m,d,x,...) m(d,296,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M296(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M298(m,d,x,...) m(d,297,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M297(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M299(m,d,x,...) m(d,298,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M298(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M300(m,d,x,...) m(d,299,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M299(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M301(m,d,x,...) m(d,300,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M300(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M302(m,d,x,...) m(d,301,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M301(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M303(m,d,x,...) m(d,302,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M302(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M304(m,d,x,...) m(d,303,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M303(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M305(m,d,x,...) m(d,304,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M304(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M306(m,d,x,...) m(d,305,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M305(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M307(m,d,x,...) m(d,306,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M306(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M308(m,d,x,...) m(d,307,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M307(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M309(m,d,x,...) m(d,308,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M308(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M310(m,d,x,...) m(d,309,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M309(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M311(m,d,x,...) m(d,310,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M310(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M312(m,d,x,...) m(d,311,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M311(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M313(m,d,x,...) m(d,312,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M312(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M314(m,d,x,...) m(d,313,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M313(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M315(m,d,x,...) m(d,314,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M314(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M316(m,d,x,...) m(d,315,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M315(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M317(m,d,x,...) m(d,316,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M316(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M318(m,d,x,...) m(d,317,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M317(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M319(m,d,x,...) m(d,318,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M318(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M320(m,d,x,...) m(d,319,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M319(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M321(m,d,x,...) m(d,320,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M320(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M322(m,d,x,...) m(d,321,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M321(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M323(m,d,x,...) m(d,322,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M322(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M324(m,d,x,...) m(d,323,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M323(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M325(m,d,x,...) m(d,324,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M324(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M326(m,d,x,...) m(d,325,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M325(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M327(m,d,x,...) m(d,326,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M326(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M328(m,d,x,...) m(d,327,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M327(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M329(m,d,x,...) m(d,328,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M328(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M330(m,d,x,...) m(d,329,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M329(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M331(m,d,x,...) m(d,330,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M330(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M332(m,d,x,...) m(d,331,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M331(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M333(m,d,x,...) m(d,332,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M332(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M334(m,d,x,...) m(d,333,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M333(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M335(m,d,x,...) m(d,334,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M334(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M336(m,d,x,...) m(d,335,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M335(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M337(m,d,x,...) m(d,336,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M336(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M338(m,d,x,...) m(d,337,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M337(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M339(m,d,x,...) m(d,338,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M338(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M340(m,d,x,...) m(d,339,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M339(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M341(m,d,x,...) m(d,340,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M340(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M342(m,d,x,...) m(d,341,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M341(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M343(m,d,x,...) m(d,342,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M342(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M344(m,d,x,...) m(d,343,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M343(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M345(m,d,x,...) m(d,344,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M344(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M346(m,d,x,...) m(d,345,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M345(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M347(m,d,x,...) m(d,346,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M346(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M348(m,d,x,...) m(d,347,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M347(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M349(m,d,x,...) m(d,348,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M348(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M350(m,d,x,...) m(d,349,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M349(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M351(m,d,x,...) m(d,350,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M350(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M352(m,d,x,...) m(d,351,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M351(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M353(m,d,x,...) m(d,352,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M352(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M354(m,d,x,...) m(d,353,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M353(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M355(m,d,x,...) m(d,354,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M354(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M356(m,d,x,...) m(d,355,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M355(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M357(m,d,x,...) m(d,356,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M356(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M358(m,d,x,...) m(d,357,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M357(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M359(m,d,x,...) m(d,358,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M358(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M360(m,d,x,...) m(d,359,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M359(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M361(m,d,x,...) m(d,360,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M360(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M362(m,d,x,...) m(d,361,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M361(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M363(m,d,x,...) m(d,362,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M362(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M364(m,d,x,...) m(d,363,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M363(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M365(m,d,x,...) m(d,364,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M364(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M366(m,d,x,...) m(d,365,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M365(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M367(m,d,x,...) m(d,366,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M366(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M368(m,d,x,...) m(d,367,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M367(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M369(m,d,x,...) m(d,368,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M368(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M370(m,d,x,...) m(d,369,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M369(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M371(m,d,x,...) m(d,370,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M370(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M372(m,d,x,...) m(d,371,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M371(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M373(m,d,x,...) m(d,372,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M372(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M374(m,d,x,...) m(d,373,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M373(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M375(m,d,x,...) m(d,374,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M374(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M376(m,d,x,...) m(d,375,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M375(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M377(m,d,x,...) m(d,376,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M376(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M378(m,d,x,...) m(d,377,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M377(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M379(m,d,x,...) m(d,378,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M378(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M380(m,d,x,...) m(d,379,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M379(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M381(m,d,x,...) m(d,380,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M380(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M382(m,d,x,...) m(d,381,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M381(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M383(m,d,x,...) m(d,382,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M382(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M384(m,d,x,...) m(d,383,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M383(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M385(m,d,x,...) m(d,384,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M384(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M386(m,d,x,...) m(d,385,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M385(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M387(m,d,x,...) m(d,386,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M386(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M388(m,d,x,...) m(d,387,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M387(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M389(m,d,x,...) m(d,388,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M388(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M390(m,d,x,...) m(d,389,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M389(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M391(m,d,x,...) m(d,390,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M390(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M392(m,d,x,...) m(d,391,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M391(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M393(m,d,x,...) m(d,392,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M392(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M394(m,d,x,...) m(d,393,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M393(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M395(m,d,x,...) m(d,394,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M394(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M396(m,d,x,...) m(d,395,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M395(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M397(m,d,x,...) m(d,396,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M396(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M398(m,d,x,...) m(d,397,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M397(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M399(m,d,x,...) m(d,398,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M398(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M400(m,d,x,...) m(d,399,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M399(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M401(m,d,x,...) m(d,400,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M400(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M402(m,d,x,...) m(d,401,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M401(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M403(m,d,x,...) m(d,402,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M402(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M404(m,d,x,...) m(d,403,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M403(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M405(m,d,x,...) m(d,404,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M404(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M406(m,d,x,...) m(d,405,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M405(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M407(m,d,x,...) m(d,406,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M406(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M408(m,d,x,...) m(d,407,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M407(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M409(m,d,x,...) m(d,408,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M408(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M410(m,d,x,...) m(d,409,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M409(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M411(m,d,x,...) m(d,410,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M410(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M412(m,d,x,...) m(d,411,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M411(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M413(m,d,x,...) m(d,412,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M412(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M414(m,d,x,...) m(d,413,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M413(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M415(m,d,x,...) m(d,414,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M414(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M416(m,d,x,...) m(d,415,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M415(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M417(m,d,x,...) m(d,416,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M416(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M418(m,d,x,...) m(d,417,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M417(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M419(m,d,x,...) m(d,418,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M418(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M420(m,d,x,...) m(d,419,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M419(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M421(m,d,x,...) m(d,420,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M420(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M422(m,d,x,...) m(d,421,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M421(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M423(m,d,x,...) m(d,422,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M422(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M424(m,d,x,...) m(d,423,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M423(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M425(m,d,x,...) m(d,424,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M424(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M426(m,d,x,...) m(d,425,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M425(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M427(m,d,x,...) m(d,426,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M426(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M428(m,d,x,...) m(d,427,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M427(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M429(m,d,x,...) m(d,428,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M428(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M430(m,d,x,...) m(d,429,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M429(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M431(m,d,x,...) m(d,430,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M430(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M432(m,d,x,...) m(d,431,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M431(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M433(m,d,x,...) m(d,432,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M432(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M434(m,d,x,...) m(d,433,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M433(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M435(m,d,x,...) m(d,434,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M434(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M436(m,d,x,...) m(d,435,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M435(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M437(m,d,x,...) m(d,436,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M436(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M438(m,d,x,...) m(d,437,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M437(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M439(m,d,x,...) m(d,438,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M438(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M440(m,d,x,...) m(d,439,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M439(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M441(m,d,x,...) m(d,440,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M440(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M442(m,d,x,...) m(d,441,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M441(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M443(m,d,x,...) m(d,442,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M442(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M444(m,d,x,...) m(d,443,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M443(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M445(m,d,x,...) m(d,444,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M444(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M446(m,d,x,...) m(d,445,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M445(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M447(m,d,x,...) m(d,446,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M446(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M448(m,d,x,...) m(d,447,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M447(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M449(m,d,x,...) m(d,448,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M448(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M450(m,d,x,...) m(d,449,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M449(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M451(m,d,x,...) m(d,450,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M450(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M452(m,d,x,...) m(d,451,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M451(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M453(m,d,x,...) m(d,452,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M452(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M454(m,d,x,...) m(d,453,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M453(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M455(m,d,x,...) m(d,454,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M454(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M456(m,d,x,...) m(d,455,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M455(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M457(m,d,x,...) m(d,456,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M456(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M458(m,d,x,...) m(d,457,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M457(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M459(m,d,x,...) m(d,458,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M458(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M460(m,d,x,...) m(d,459,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M459(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M461(m,d,x,...) m(d,460,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M460(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M462(m,d,x,...) m(d,461,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M461(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M463(m,d,x,...) m(d,462,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M462(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M464(m,d,x,...) m(d,463,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M463(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M465(m,d,x,...) m(d,464,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M464(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M466(m,d,x,...) m(d,465,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M465(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M467(m,d,x,...) m(d,466,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M466(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M468(m,d,x,...) m(d,467,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M467(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M469(m,d,x,...) m(d,468,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M468(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M470(m,d,x,...) m(d,469,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M469(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M471(m,d,x,...) m(d,470,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M470(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M472(m,d,x,...) m(d,471,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M471(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M473(m,d,x,...) m(d,472,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M472(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M474(m,d,x,...) m(d,473,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M473(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M475(m,d,x,...) m(d,474,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M474(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M476(m,d,x,...) m(d,475,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M475(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M477(m,d,x,...) m(d,476,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M476(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M478(m,d,x,...) m(d,477,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M477(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M479(m,d,x,...) m(d,478,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M478(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M480(m,d,x,...) m(d,479,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M479(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M481(m,d,x,...) m(d,480,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M480(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M482(m,d,x,...) m(d,481,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M481(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M483(m,d,x,...) m(d,482,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M482(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M484(m,d,x,...) m(d,483,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M483(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M485(m,d,x,...) m(d,484,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M484(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M486(m,d,x,...) m(d,485,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M485(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M487(m,d,x,...) m(d,486,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M486(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M488(m,d,x,...) m(d,487,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M487(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M489(m,d,x,...) m(d,488,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M488(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M490(m,d,x,...) m(d,489,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M489(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M491(m,d,x,...) m(d,490,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M490(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M492(m,d,x,...) m(d,491,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M491(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M493(m,d,x,...) m(d,492,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M492(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M494(m,d,x,...) m(d,493,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M493(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M495(m,d,x,...) m(d,494,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M494(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M496(m,d,x,...) m(d,495,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M495(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M497(m,d,x,...) m(d,496,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M496(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M498(m,d,x,...) m(d,497,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M497(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M499(m,d,x,...) m(d,498,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M498(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M500(m,d,x,...) m(d,499,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M499(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M501(m,d,x,...) m(d,500,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M500(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M502(m,d,x,...) m(d,501,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M501(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M503(m,d,x,...) m(d,502,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M502(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M504(m,d,x,...) m(d,503,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M503(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M505(m,d,x,...) m(d,504,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M504(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M506(m,d,x,...) m(d,505,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M505(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M507(m,d,x,...) m(d,506,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M506(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M508(m,d,x,...) m(d,507,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M507(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M509(m,d,x,...) m(d,508,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M508(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M510(m,d,x,...) m(d,509,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M509(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M511(m,d,x,...) m(d,510,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M510(m,d,__VA_ARGS__))
#define BETTER_ENUMS_M512(m,d,x,...) m(d,511,x) \
    BETTER_ENUMS_ID(BETTER_ENUMS_M511(m,d,__VA_ARGS__))

#define BETTER_ENUMS_PP_COUNT_IMPL(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10,    \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, \
    _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, \
    _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, \
    _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, \
    _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100,\
    _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112,    \
    _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124,    \
    _125, _126, _127, _128, _129, _130, _131, _132, _133, _134, _135, _136,    \
    _137, _138, _139, _140, _141, _142, _143, _144, _145, _146, _147, _148,    \
    _149, _150, _151, _152, _153, _154, _155, _156, _157, _158, _159, _160,    \
    _161, _162, _163, _164, _165, _166, _167, _168, _169, _170, _171, _172,    \
    _173, _174, _175, _176, _177, _178, _179, _180, _181, _182, _183, _184,    \
    _185, _186, _187, _188, _189, _190, _191, _192, _193, _194, _195, _196,    \
    _197, _198, _199, _200, _201, _202, _203, _204, _205, _206, _207, _208,    \
    _209, _210, _211, _212, _213, _214, _215, _216, _217, _218, _219, _220,    \
    _221, _222, _223, _224, _225, _226, _227, _228, _229, _230, _231, _232,    \
    _233, _234, _235, _236, _237, _238, _239, _240, _241, _242, _243, _244,    \
    _245, _246, _247, _248, _249, _250, _251, _252, _253, _254, _255, _256,    \
    _257, _258, _259, _260, _261, _262, _263, _264, _265, _266, _267, _268,    \
    _269, _270, _271, _272, _273, _274, _275, _276, _277, _278, _279, _280,    \
    _281, _282, _283, _284, _285, _286, _287, _288, _289, _290, _291, _292,    \
    _293, _294, _295, _296, _297, _298, _299, _300, _301, _302, _303, _304,    \
    _305, _306, _307, _308, _309, _310, _311, _312, _313, _314, _315, _316,    \
    _317, _318, _319, _320, _321, _322, _323, _324, _325, _326, _327, _328,    \
    _329, _330, _331, _332, _333, _334, _335, _336, _337, _338, _339, _340,    \
    _341, _342, _343, _344, _345, _346, _347, _348, _349, _350, _351, _352,    \
    _353, _354, _355, _356, _357, _358, _359, _360, _361, _362, _363, _364,    \
    _365, _366, _367, _368, _369, _370, _371, _372, _373, _374, _375, _376,    \
    _377, _378, _379, _380, _381, _382, _383, _384, _385, _386, _387, _388,    \
    _389, _390, _391, _392, _393, _394, _395, _396, _397, _398, _399, _400,    \
    _401, _402, _403, _404, _405, _406, _407, _408, _409, _410, _411, _412,    \
    _413, _414, _415, _416, _417, _418, _419, _420, _421, _422, _423, _424,    \
    _425, _426, _427, _428, _429, _430, _431, _432, _433, _434, _435, _436,    \
    _437, _438, _439, _440, _441, _442, _443, _444, _445, _446, _447, _448,    \
    _449, _450, _451, _452, _453, _454, _455, _456, _457, _458, _459, _460,    \
    _461, _462, _463, _464, _465, _466, _467, _468, _469, _470, _471, _472,    \
    _473, _474, _475, _476, _477, _478, _479, _480, _481, _482, _483, _484,    \
    _485, _486, _487, _488, _489, _490, _491, _492, _493, _494, _495, _496,    \
    _497, _498, _499, _500, _501, _502, _503, _504, _505, _506, _507, _508,    \
    _509, _510, _511, _512, count, ...) count

#define BETTER_ENUMS_PP_COUNT(...) \
    BETTER_ENUMS_ID(BETTER_ENUMS_PP_COUNT_IMPL(__VA_ARGS__, 512, 511, 510, 509,\
        508, 507, 506, 505, 504, 503, 502, 501, 500, 499, 498, 497, 496, 495,  \
        494, 493, 492, 491, 490, 489, 488, 487, 486, 485, 484, 483, 482, 481,  \
        480, 479, 478, 477, 476, 475, 474, 473, 472, 471, 470, 469, 468, 467,  \
        466, 465, 464, 463, 462, 461, 460, 459, 458, 457, 456, 455, 454, 453,  \
        452, 451, 450, 449, 448, 447, 446, 445, 444, 443, 442, 441, 440, 439,  \
        438, 437, 436, 435, 434, 433, 432, 431, 430, 429, 428, 427, 426, 425,  \
        424, 423, 422, 421, 420, 419, 418, 417, 416, 415, 414, 413, 412, 411,  \
        410, 409, 408, 407, 406, 405, 404, 403, 402, 401, 400, 399, 398, 397,  \
        396, 395, 394, 393, 392, 391, 390, 389, 388, 387, 386, 385, 384, 383,  \
        382, 381, 380, 379, 378, 377, 376, 375, 374, 373, 372, 371, 370, 369,  \
        368, 367, 366, 365, 364, 363, 362, 361, 360, 359, 358, 357, 356, 355,  \
        354, 353, 352, 351, 350, 349, 348, 347, 346, 345, 344, 343, 342, 341,  \
        340, 339, 338, 337, 336, 335, 334, 333, 332, 331, 330, 329, 328, 327,  \
        326, 325, 324, 323, 322, 321, 320, 319, 318, 317, 316, 315, 314, 313,  \
        312, 311, 310, 309, 308, 307, 306, 305, 304, 303, 302, 301, 300, 299,  \
        298, 297, 296, 295, 294, 293, 292, 291, 290, 289, 288, 287, 286, 285,  \
        284, 283, 282, 281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271,  \
        270, 269, 268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257,  \
        256, 255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,  \
        242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230, 229,  \
        228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217, 216, 215,  \
        214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203, 202, 201,  \
        200, 199, 198, 197, 196, 195, 194, 193, 192, 191, 190, 189, 188, 187,  \
        186, 185, 184, 183, 182, 181, 180, 179, 178, 177, 176, 175, 174, 173,  \
        172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, 160, 159,  \
        158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146, 145,  \
        144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134, 133, 132, 131,  \
        130, 129, 128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117,  \
        116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103,  \
        102, 101, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, \
        85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68,\
        67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,\
        49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,\
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,\
        13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1))

#define BETTER_ENUMS_ITERATE(X, f, l) X(f, l, 0) X(f, l, 1) X(f, l, 2)         \
    X(f, l, 3) X(f, l, 4) X(f, l, 5) X(f, l, 6) X(f, l, 7) X(f, l, 8)          \
    X(f, l, 9) X(f, l, 10) X(f, l, 11) X(f, l, 12) X(f, l, 13) X(f, l, 14)     \
    X(f, l, 15) X(f, l, 16) X(f, l, 17) X(f, l, 18) X(f, l, 19) X(f, l, 20)    \
    X(f, l, 21) X(f, l, 22) X(f, l, 23) X(f, l, 24) X(f, l, 25) X(f, l, 26)    \
    X(f, l, 27) X(f, l, 28) X(f, l, 29) X(f, l, 30) X(f, l, 31) X(f, l, 32)    \
    X(f, l, 33) X(f, l, 34) X(f, l, 35) X(f, l, 36) X(f, l, 37) X(f, l, 38)    \
    X(f, l, 39) X(f, l, 40) X(f, l, 41) X(f, l, 42) X(f, l, 43) X(f, l, 44)    \
    X(f, l, 45) X(f, l, 46) X(f, l, 47) X(f, l, 48) X(f, l, 49) X(f, l, 50)    \
    X(f, l, 51) X(f, l, 52) X(f, l, 53) X(f, l, 54) X(f, l, 55) X(f, l, 56)    \
    X(f, l, 57) X(f, l, 58) X(f, l, 59) X(f, l, 60) X(f, l, 61) X(f, l, 62)    \
    X(f, l, 63)

#endif // #ifndef BETTER_ENUMS_MACRO_FILE_H
