name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          # Windows Server 2025 + Visual Studio 2026
          - name: "Windows Server 2025 + Visual Studio 2026"
            os: windows-2025-vs2026
            solution: RosettaStone.slnx
          # Windows Server 2022 + Visual Studio 2022
          - name: "Windows Server 2022 + Visual Studio 2022"
            os: windows-2022
            solution: RosettaStone.sln

    runs-on: ${{ matrix.os }}
    name: 🪟 Build - ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release ..
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: cd build && MSBuild.exe ${{ matrix.solution }} /p:Configuration=Release
    - name: Run Unit Test
      run: /a/RosettaStone/RosettaStone/build/bin/Release/UnitTests.exe
    - name: Run Python Test
      run: |
        pip install -r requirements.txt --break-system-packages
        pip install . --break-system-packages
        python -m pytest Tests/PythonTests/
